// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpYucaq-969OqFpC_5H_AXuLI7XAUnrtM',
    appId: '1:367973413886:web:7aa478434952b78ccd06af',
    messagingSenderId: '367973413886',
    projectId: 'simple-c0e89',
    authDomain: 'simple-c0e89.firebaseapp.com',
    storageBucket: 'simple-c0e89.firebasestorage.app',
    measurementId: 'G-Q6M02HH9JM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtM-n3MhukQu-s6gz7Bp77Y2XKNZv4sU0',
    appId: '1:367973413886:android:ea652b13f5672e71cd06af',
    messagingSenderId: '367973413886',
    projectId: 'simple-c0e89',
    storageBucket: 'simple-c0e89.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHPIDJlYv_M4HKQHDcc2yPjjsx1ClCD-0',
    appId: '1:367973413886:ios:25e15b7ce1cc509acd06af',
    messagingSenderId: '367973413886',
    projectId: 'simple-c0e89',
    storageBucket: 'simple-c0e89.firebasestorage.app',
    iosBundleId: 'com.example.completeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHPIDJlYv_M4HKQHDcc2yPjjsx1ClCD-0',
    appId: '1:367973413886:ios:25e15b7ce1cc509acd06af',
    messagingSenderId: '367973413886',
    projectId: 'simple-c0e89',
    storageBucket: 'simple-c0e89.firebasestorage.app',
    iosBundleId: 'com.example.completeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpYucaq-969OqFpC_5H_AXuLI7XAUnrtM',
    appId: '1:367973413886:web:cd4374c666bd1799cd06af',
    messagingSenderId: '367973413886',
    projectId: 'simple-c0e89',
    authDomain: 'simple-c0e89.firebaseapp.com',
    storageBucket: 'simple-c0e89.firebasestorage.app',
    measurementId: 'G-QD5DNSLYXT',
  );
}
